version: '3'

services:
  db:
    image: postgres:12.0-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py create_test_data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
