# Generated by Django 4.2.6 on 2023-10-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_groups.customgroup'),
        ),
    ]
