# Generated by Django 4.2.6 on 2023-10-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0002_alter_customuser_custom_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
